### PR TITLE
Add workflow to prevent additions to the Terraform SDK folder

### PR DESCRIPTION
**Pull request by mjhilton**
Fairly self-explanatory. Detects additions only, allows deletions and modifications.

Example successful run:
image

Example failed run:
image
image

### CODE REVIEW

**Comment by denys-octopus** [comment]
Nice 👍 Looks good. Sorry would this action failing prevent branch from merging?

**Review by denys-octopus — APPROVED** [review]

**Comment by mjhilton** [comment]
> Nice 👍 Looks good. Sorry would this action failing prevent branch from merging?

Not 100% sure how GHA works in this sense. I don't think so, I think you need to specifically mark a workflow as "required" in GH before it'll block merges.

**Comment by mjhilton** [comment]
Yep. We can choose to configure this as a blocking workflow if we want:
image

**Comment by mjhilton** [comment]
Might keep it optional for a few PRs to ensure it works well, and think about adding it as mandatory in 2025.

**Pull request merged**
